version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_ACTIVEMQ_BROKER_URL=tcp://activemq:61616
      - SPRING_ACTIVEMQ_USER=admin
      - SPRING_ACTIVEMQ_PASSWORD=admin
    depends_on:
      - activemq

  activemq:
    image: rmohr/activemq:latest  # Use a imagem recomendada
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      - ACTIVEMQ_USER=admin
      - ACTIVEMQ_PASSWORD=admin
    volumes:
      - activemq-data:/var/lib/activemq  # Persistência de dados
    networks:
      - activemq-network

volumes:
  activemq-data:  # Volume para persistência de dados

networks:
  activemq-network:
    driver: bridge

